project_name: "cinful"

builds:
- binary: "cinful"
  main: cmd/cinful/main.go

  ldflags:
    - -s -w
  env:
  - CGO_ENABLED=0

  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm64

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}"

archives:
- format: binary
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  # Needed hack for binary only uploads
  # For more information, check #602
  files:
   - "thisfiledoesnotexist*"


checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'


release:
  disable: false
  draft: false
  github:
    owner: hofstadter-io
    name: cinful
